// flow-typed signature: 573364c6ba1208b7d2ee45236acc8770
// flow-typed version: <<STUB>>/del-cli_v^0.2.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'del-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'del-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'del-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'del-cli/cli.js' {
  declare module.exports: $Exports<'del-cli/cli'>;
}
