// flow-typed signature: aceb6ccd73bf14ac4facc84b73d1844c
// flow-typed version: <<STUB>>/standard-changelog_v^2.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-changelog/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-changelog/cli.js' {
  declare module.exports: $Exports<'standard-changelog/cli'>;
}
declare module 'standard-changelog/index' {
  declare module.exports: $Exports<'standard-changelog'>;
}
declare module 'standard-changelog/index.js' {
  declare module.exports: $Exports<'standard-changelog'>;
}
